import { VisaType } from '@/types/visas.type';

export const visas: VisaType[] = [
  {
    id: 'h1b',
    name: 'H-1B Work Visa',
    description: 'For foreign workers in specialty occupations',
    country: 'United States',
    requirements: [
      {
        id: 'edu',
        title: "Bachelor's degree or higher",
        description: "Bachelor's degree or higher in related field",
        estimatedTime: '1-2 weeks',
        documents: ['Degree Certificate', 'Transcripts', 'Evaluations'],
      },
      {
        id: 'emp',
        title: 'Job offer from US employer',
        description: 'Valid job offer from US employer',
        estimatedTime: '2-3 weeks',
        documents: [
          'Job Offer Letter',
          'Employment Contract',
          'Company Documents',
        ],
      },
      {
        id: 'spec',
        title: 'Specialty occupation position',
        description: 'Specialty occupation position',
        estimatedTime: '2-3 weeks',
        documents: ['Specialty occupation position'],
      },
      {
        id: 'prev',
        title: 'Prevailing wage requirement',
        description: 'Prevailing wage requirement',
        estimatedTime: '2-3 weeks',
        documents: ['Prevailing wage requirement'],
      },
    ],
    curators: [
      { id: '1', name: 'Sarah Johnson', initials: 'SJ' },
      { id: '2', name: 'Michael Chen', initials: 'MC' },
      { id: '3', name: 'David Kim', initials: 'DK' },
    ],
    img: 'US',
    agents: ['agent1', 'agent2'],
    processingTime: '6-8 months',
    price: 460,
  },
  {
    id: 'f1',
    country: 'United States',
    name: 'F-1 Student Visa',
    description: 'For international students studying in the US',
    requirements: [
      {
        id: 'edu',
        title: 'University acceptance letter',
        description: 'University acceptance letter',
        estimatedTime: '1-2 weeks',
        documents: ['University acceptance letter'],
      },
      {
        id: 'fin',
        title: 'Financial documents',
        description: 'Financial documents',
        estimatedTime: '1-2 weeks',
        documents: ['Financial documents'],
      },
      {
        id: 'sevis',
        title: 'SEVIS I-20 form',
        description: 'SEVIS I-20 form',
        estimatedTime: '1-2 weeks',
        documents: ['SEVIS I-20 form'],
      },
      {
        id: 'eng',
        title: 'English proficiency test',
        description: 'English proficiency test',
        estimatedTime: '1-2 weeks',
        documents: ['English proficiency test'],
      },
    ],
    curators: [
      { id: '1', name: 'Sarah Johnson', initials: 'SJ' },
      { id: '4', name: 'Emily Wang', initials: 'EW' },
    ],
    img: 'US',
    agents: ['agent1', 'agent2'],
    processingTime: '6-8 months',
    price: 350,
  },
  {
    id: 'b2',
    country: 'United States',
    name: 'B-2 Visa',
    description: 'For temporary visitors to the US',
    requirements: [
      {
        id: 'edu',
        title: 'University acceptance letter',
        description: 'University acceptance letter',
        estimatedTime: '1-2 weeks',
        documents: ['University acceptance letter'],
      },
      {
        id: 'fin',
        title: 'Financial documents',
        description: 'Financial documents',
        estimatedTime: '1-2 weeks',
        documents: ['Financial documents'],
      },
      {
        id: 'sevis',
        title: 'SEVIS I-20 form',
        description: 'SEVIS I-20 form',
        estimatedTime: '1-2 weeks',
        documents: ['SEVIS I-20 form'],
      },
      {
        id: 'eng',
        title: 'English proficiency test',
        description: 'English proficiency test',
        estimatedTime: '1-2 weeks',
        documents: ['English proficiency test'],
      },
    ],
    curators: [
      { id: '1', name: 'Sarah Johnson', initials: 'SJ' },
      { id: '4', name: 'Emily Wang', initials: 'EW' },
    ],
    img: 'US',
    agents: ['agent1', 'agent2'],
    processingTime: '6-8 months',
    price: 350,
  },
  {
    id: 'h2a',
    country: 'United States',
    name: 'H-2A Visa',
    description: 'For temporary agricultural workers in the US',
    requirements: [
      {
        id: 'edu',
        title: 'University acceptance letter',
        description: 'University acceptance letter',
        estimatedTime: '1-2 weeks',
        documents: ['University acceptance letter'],
      },
      {
        id: 'fin',
        title: 'Financial documents',
        description: 'Financial documents',
        estimatedTime: '1-2 weeks',
        documents: ['Financial documents'],
      },
      {
        id: 'sevis',
        title: 'SEVIS I-20 form',
        description: 'SEVIS I-20 form',
        estimatedTime: '1-2 weeks',
        documents: ['SEVIS I-20 form'],
      },
      {
        id: 'eng',
        title: 'English proficiency test',
        description: 'English proficiency test',
        estimatedTime: '1-2 weeks',
        documents: ['English proficiency test'],
      },
    ],
    curators: [
      { id: '1', name: 'Sarah Johnson', initials: 'SJ' },
      { id: '4', name: 'Emily Wang', initials: 'EW' },
    ],
    img: 'US',
    agents: ['agent1', 'agent2'],
    processingTime: '6-8 months',
    price: 350,
  },
  {
    id: 'h2b',
    country: 'United States',
    name: 'H-2B Visa',
    description: 'For temporary non-agricultural workers in the US',
    requirements: [
      {
        id: 'edu',
        title: 'University acceptance letter',
        description: 'University acceptance letter',
        estimatedTime: '1-2 weeks',
        documents: ['University acceptance letter'],
      },
      {
        id: 'fin',
        title: 'Financial documents',
        description: 'Financial documents',
        estimatedTime: '1-2 weeks',
        documents: ['Financial documents'],
      },
      {
        id: 'sevis',
        title: 'SEVIS I-20 form',
        description: 'SEVIS I-20 form',
        estimatedTime: '1-2 weeks',
        documents: ['SEVIS I-20 form'],
      },
      {
        id: 'eng',
        title: 'English proficiency test',
        description: 'English proficiency test',
        estimatedTime: '1-2 weeks',
        documents: ['English proficiency test'],
      },
    ],
    curators: [
      { id: '1', name: 'Sarah Johnson', initials: 'SJ' },
      { id: '4', name: 'Emily Wang', initials: 'EW' },
    ],
    img: 'US',
    agents: ['agent1', 'agent2'],
    processingTime: '6-8 months',
    price: 350,
  },
];
